# Generated by Django 3.2.25 on 2025-03-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20250318_1831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
