# Generated by Django 4.2 on 2025-04-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20250320_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=' ../default_profile_eb3bey', upload_to='images/'),
        ),
    ]
