# Generated by Django 4.2 on 2025-04-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dmjs4rot0/image/upload/v1744296769/default_profile_eb3bey.jpg', upload_to=''),
        ),
    ]
