# Generated by Django 4.2 on 2025-04-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
